name: Deploy Django with Docker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        run: |
          scp -r -o StrictHostKeyChecking=no ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/mysite/

      - name: Docker compose operations
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /var/www/mysite
            docker compose down
            docker compose pull
            docker compose build --no-cache
            docker compose up -d
            docker exec -it django_container python manage.py migrate
            docker exec -it django_container python manage.py collectstatic --no-input
          "